quarkus.mongodb.connection-string=${DB_URL:mongodb://localhost:27017}

quarkus.mongodb.credentials.username=${DB_USER}
quarkus.mongodb.credentials.password=${DB_PASSWORD}
quarkus.mongodb.database=${DB_NAME}
quarkus.mongodb.credentials.auth-source=admin

quarkus.http.port=${PORT:8080}
biological-object-api/mp-rest/url=${BIOLOGICAL_OBJECTS:http://search-biological-objects:8080}