quarkus.http.access-log.enabled=true
quarkus.mongodb.connection-string=${DB_URL:mongodb://localhost:27017}

quarkus.mongodb.credentials.username=${DB_USER}
quarkus.mongodb.credentials.password=${DB_PASSWORD}
quarkus.mongodb.database=${DB_NAME}
quarkus.mongodb.credentials.auth-source=admin
quarkus.http.port=${PORT:8080}

mp.fault.tolerance.global.Retry/maxRetries=5
mp.fault.tolerance.global.Retry/delay=1000

quarkus.rest-client.keycloak-auth-api.url=${KC_URL}
quarkus.rest-client.keycloak-auth-api.scope=jakarta.enterprise.context.ApplicationScoped

keycloak.client.id=${KC_CLIENT_ID}
keycloak.client.secret=${KC_CLIENT_SECRET}
keycloak.grant-type=${KC_GRANT_TYPE_USER}
keycloak.grant-type-client=${KC_GRANT_TYPE_CLIENT}
keycloak.scope=${KC_SCOPE}

biological-object-api/mp-rest/url=${BIOLOGICAL_OBJECTS:http://search-biological-objects:8080}